/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface-dim": "#0b1326",
        "secondary-fixed-dim": "#bcc7de",
        "surface-variant": "#2d3449",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#00885d",
        "inverse-primary": "#494bd6",
        "on-background": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#e1e0ff",
        "on-primary-container": "#0d0096",
        "on-surface-variant": "#c7c4d7",
        "secondary": "#bcc7de",
        "on-surface": "#dae2fd",
        "surface-bright": "#31394d",
        "on-primary-fixed": "#07006c",
        "primary-container": "#8083ff",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#131b2e",
        "outline": "#908fa0",
        "surface-container-highest": "#2d3449",
        "outline-variant": "#464554",
        "primary-fixed-dim": "#c0c1ff",
        "surface-tint": "#c0c1ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container": "#171f33",
        "on-secondary-fixed-variant": "#3c475a",
        "secondary-container": "#3e495d",
        "surface": "#0b1326",
        "inverse-on-surface": "#283044",
        "error": "#ffb4ab",
        "on-primary": "#1000a9",
        "on-tertiary": "#003824",
        "on-error": "#690005",
        "on-tertiary-container": "#000703",
        "on-tertiary-fixed-variant": "#005236",
        "inverse-surface": "#dae2fd",
        "on-secondary-fixed": "#111c2d",
        "surface-container-high": "#222a3d",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-container": "#aeb9d0",
        "primary": "#c0c1ff",
        "on-secondary": "#263143",
        "on-primary-fixed-variant": "#2f2ebe",
        "background": "#0b1326"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"
      },
    },
  },
  plugins: [],
}